from django.contrib import admin
from django.urls import path

from backend.core import (
    account_api,
    api,
    experience_api,
    match_api,
    operations_api,
    pilot_api,
    recording_api,
)
from backend.core.cloud_api import dispatch_task
from backend.core.deployment import health

urlpatterns = [
    path("health/ready", health),
    path("internal/dispatch", dispatch_task),
    path("admin/", admin.site.urls),
    path("api/session", api.session),
    path("api/account/policy", account_api.policy),
    path("api/account/register", account_api.registration),
    path("api/account/link", account_api.request_link),
    path("api/account/confirm", account_api.confirm),
    path("api/account/details", account_api.account_details),
    path("api/account/password", account_api.password_change),
    path("api/account/email", account_api.email_change),
    path("api/account/logout-all", account_api.logout_all),
    path("api/account/sessions/<uuid:session_id>", account_api.revoke_session),
    path("api/account/consent", account_api.consent),
    path("api/overview", api.overview),
    path("api/operations", operations_api.operations),
    path("api/operations/work", operations_api.work),
    path("api/operations/cost", operations_api.cost),
    path("api/usage", operations_api.usage),
    path("api/pilots", pilot_api.studies),
    path("api/pilot-invitation", pilot_api.inspect_invitation),
    path("api/pilot-join", pilot_api.join),
    path("api/pilots/<uuid:study_id>", pilot_api.study_detail),
    path("api/pilots/<uuid:study_id>/tasks/<uuid:task_id>/media", pilot_api.media),
    path("api/pilots/<uuid:study_id>/<str:operation>", pilot_api.command),
    path("api/preferences", experience_api.preferences),
    path("api/evidence", experience_api.evidence),
    path("api/feedback", experience_api.feedback),
    path("api/notices", experience_api.notices),
    path("api/account/export", experience_api.export_account),
    path("api/account", experience_api.remove_account),
    path("api/match-providers", match_api.providers),
    path("api/player-candidates", match_api.candidates),
    path("api/player-identities", match_api.identities),
    path("api/player-identities/<uuid:identity_id>", match_api.unlink_identity),
    path("api/player-identities/<uuid:identity_id>/sync", match_api.sync_identity),
    path("api/match-syncs/<uuid:sync_id>", match_api.sync_detail),
    path("api/matches", match_api.history),
    path("api/matches/<uuid:match_id>", match_api.remove_match),
    path("api/matches/<uuid:match_id>/recordings", recording_api.upload_recording),
    path(
        "api/matches/<uuid:match_id>/recordings/<uuid:source_id>/reprocess", recording_api.reprocess
    ),
    path("api/uploads", api.upload),
    path("api/runs/<uuid:run_id>", api.run_detail),
    path("api/assets/<uuid:asset_id>", api.asset_delete),
    path("api/assets/<uuid:asset_id>/media", api.media),
    path("api/assignments", api.assignments),
    path("api/plans", api.plans),
    path("api/assignments/<uuid:assignment_id>/practice", api.practice),
    path("api/plans/<uuid:plan_id>/evaluate", api.evaluations),
]
