# Generated by Django 5.2.17 on 2026-09-18 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionVersion',
            fields=[
                ('key', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('move', 'move'), ('knowledge', 'knowledge'), ('situation', 'situation'), ('metric', 'metric'), ('drill', 'drill'), ('capture', 'capture')], max_length=30)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_version', models.CharField(default='local-pipeline/1', max_length=80)),
                ('request_key', models.CharField(max_length=100)),
                ('status', models.CharField(default='QUEUED', max_length=30)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('fence', models.PositiveIntegerField(default=0)),
                ('lease_until', models.DateTimeField(null=True)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrillAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ASSIGNED', max_length=30)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.definitionversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specification', models.JSONField()),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.drillassignment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameBuild',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('provenance', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.game')),
            ],
        ),
        migrations.AddField(
            model_name='definitionversion',
            name='game_build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gamebuild'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_build', models.CharField(max_length=80)),
                ('knowledge_revision', models.CharField(max_length=160)),
                ('session_id', models.CharField(max_length=100)),
                ('played_at', models.DateTimeField()),
                ('chronology_verified', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('ranked', 'ranked'), ('practice', 'practice'), ('takeover', 'takeover')], max_length=20)),
                ('context', models.CharField(default='jin/jin', max_length=100)),
                ('dataset_kind', models.CharField(default='real', max_length=20)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameplayEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('played_key', models.CharField(max_length=180)),
                ('situation', models.CharField(max_length=160)),
                ('metric', models.CharField(max_length=160)),
                ('detector_version', models.CharField(max_length=100)),
                ('start_us', models.PositiveBigIntegerField()),
                ('end_us', models.PositiveBigIntegerField()),
                ('eligibility', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('evidence', models.JSONField(default=list)),
                ('review', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.analysisrun')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.analysisrun')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=160)),
                ('summary', models.JSONField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.character')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=250)),
                ('content_hash', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=50)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('character', models.CharField(max_length=50)),
                ('is_player', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('processing_consent_at', models.DateTimeField(null=True)),
                ('training_consent_at', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(max_length=160)),
                ('metric', models.CharField(max_length=160)),
                ('baseline_event_ids', models.JSONField()),
                ('summary', models.JSONField()),
                ('state', models.CharField(default='PROPOSED', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='drillassignment',
            name='recommendation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.recommendation'),
        ),
        migrations.CreateModel(
            name='ReplayAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_key', models.CharField(max_length=250)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('bytes', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('purge_completed_at', models.DateTimeField(null=True)),
                ('upload_session', models.TextField(blank=True)),
                ('upload_cancelled', models.BooleanField(default=False)),
                ('retain_until', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.replayasset'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.replayasset'),
        ),
        migrations.CreateModel(
            name='ReplaySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_us', models.PositiveBigIntegerField()),
                ('end_us', models.PositiveBigIntegerField()),
                ('mode', models.CharField(max_length=20)),
                ('round_ordinal', models.PositiveSmallIntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.replayasset')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('mode', models.CharField(default='recorded_in_game', max_length=40)),
                ('setup', models.JSONField(default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drillassignment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrillAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_index', models.PositiveIntegerField()),
                ('source_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.gameplayevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.PositiveIntegerField()),
                ('result', models.JSONField()),
                ('invalidated_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.evaluationplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'revision'), name='unique_evaluation_revision')],
            },
        ),
        migrations.AddIndex(
            model_name='gameplayevent',
            index=models.Index(fields=['owner', 'match', 'start_us'], name='core_gamepl_owner_i_4f485f_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameplayevent',
            constraint=models.UniqueConstraint(fields=('run', 'match', 'played_key'), name='unique_opportunity_revision'),
        ),
        migrations.AddConstraint(
            model_name='gameplayevent',
            constraint=models.CheckConstraint(condition=models.Q(('end_us__gte', models.F('start_us'))), name='event_time_order'),
        ),
        migrations.AddConstraint(
            model_name='gameplayevent',
            constraint=models.CheckConstraint(condition=models.Q(('eligibility__in', ['ELIGIBLE', 'INELIGIBLE', 'UNKNOWN'])), name='valid_eligibility'),
        ),
        migrations.AddConstraint(
            model_name='gameplayevent',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['SUCCESS', 'FAILURE', 'UNKNOWN'])), name='valid_outcome'),
        ),
        migrations.AddConstraint(
            model_name='gameplayevent',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', 'UNKNOWN'), models.Q(('eligibility', 'ELIGIBLE'), ('verified', True)), _connector='OR'), name='known_outcome_requires_eligible_verified'),
        ),
        migrations.AddConstraint(
            model_name='matchcontribution',
            constraint=models.UniqueConstraint(fields=('match', 'metric'), name='one_active_contribution'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('match', 'slot'), name='unique_match_slot'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('slot__in', [1, 2])), name='two_supported_slots'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(fields=('owner', 'request_key'), name='run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='replaysegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_us__gte', models.F('start_us'))), name='segment_time_order'),
        ),
        migrations.AddConstraint(
            model_name='drillattempt',
            constraint=models.UniqueConstraint(fields=('session', 'trial_index'), name='unique_trial'),
        ),
    ]
