# Generated by Django 5.2.17 on 2026-09-19 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attempt_played_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.game'),
        ),
        migrations.AddField(
            model_name='match',
            name='metadata_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='metadata_state',
            field=models.CharField(default='USER_UPLOAD', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_slot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='match',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.replayasset'),
        ),
        migrations.AlterField(
            model_name='match',
            name='context',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_build',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='knowledge_revision',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('unknown', 'unknown'), ('ranked', 'ranked'), ('quick', 'quick'), ('player', 'player'), ('group', 'group'), ('practice', 'practice'), ('takeover', 'takeover'), ('other', 'other')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='character',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MatchSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=100)),
                ('policy_version', models.CharField(max_length=100)),
                ('access_class', models.CharField(max_length=40)),
                ('external_namespace', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=200)),
                ('revision', models.PositiveIntegerField()),
                ('retrieved_at', models.DateTimeField()),
                ('raw_digest', models.CharField(max_length=64)),
                ('normalized_digest', models.CharField(max_length=64)),
                ('adapter_version', models.CharField(max_length=100)),
                ('schema_version', models.CharField(max_length=100)),
                ('assertion', models.JSONField()),
                ('correction_state', models.CharField(default='ACCEPTED', max_length=30)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='core.match')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('namespace', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('display_label', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(default='CLAIMED', max_length=20)),
                ('consent_scope', models.CharField(max_length=100)),
                ('provenance', models.JSONField(default=dict)),
                ('verification', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=100)),
                ('policy_version', models.CharField(max_length=100)),
                ('query_start', models.DateTimeField()),
                ('query_end', models.DateTimeField()),
                ('checkpoint', models.TextField(null=True)),
                ('coverage', models.JSONField(default=list)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('fence', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_until', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('last_succeeded_at', models.DateTimeField(null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playergameidentity')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.playergameidentity'),
        ),
        migrations.CreateModel(
            name='ReplaySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('access_class', models.CharField(max_length=40)),
                ('representation', models.CharField(max_length=30)),
                ('external_id', models.JSONField(null=True)),
                ('availability', models.CharField(default='UNKNOWN', max_length=30)),
                ('checked_at', models.DateTimeField(null=True)),
                ('upstream_expires_at', models.DateTimeField(null=True)),
                ('local_retain_until', models.DateTimeField(null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('canonical_build', models.CharField(max_length=80, null=True)),
                ('parser_version', models.CharField(max_length=100, null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.replayasset')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_sources', to='core.match')),
                ('source_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matchsourcerecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchsourcerecord',
            constraint=models.UniqueConstraint(fields=('owner', 'provider', 'external_namespace', 'external_id', 'revision'), name='source_record_revision'),
        ),
        migrations.AddConstraint(
            model_name='playergameidentity',
            constraint=models.UniqueConstraint(fields=('owner', 'game', 'namespace', 'value'), name='owner_game_identity'),
        ),
        migrations.AddConstraint(
            model_name='matchsync',
            constraint=models.UniqueConstraint(fields=('owner', 'identity', 'provider', 'query_start', 'query_end'), name='sync_query_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='replaysource',
            constraint=models.UniqueConstraint(fields=('match', 'asset'), name='one_upload_representation'),
        ),
    ]
