# Generated by Django 5.2.17 on 2026-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_upload_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaysource',
            name='attribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='replaysource',
            name='attribution_state',
            field=models.CharField(default='NOT_REQUIRED', max_length=30),
        ),
    ]
