# Generated by Django 5.2.17 on 2026-09-23 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recording_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='analysis_notices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_timezone',
            field=models.CharField(default='UTC', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='followup_notices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='practice_notices',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('request_id', models.UUIDField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gameplayevent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'request_id'), name='feedback_request')],
            },
        ),
        migrations.CreateModel(
            name='NoticeReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'key'), name='notice_receipt')],
            },
        ),
    ]
