# Generated by Django 5.2.17 on 2026-09-30 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def capture_legacy_receipts(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    Receipt = apps.get_model('core', 'ConsentReceipt')
    for profile in Profile.objects.using(schema_editor.connection.alias).iterator():
        for scope, date in [('PROCESSING', profile.processing_consent_at), ('TRAINING', profile.training_consent_at)]:
            if date and not profile.deleted_at:
                receipt = Receipt.objects.using(schema_editor.connection.alias).create(
                    owner_id=profile.user_id, scope=scope, action='GRANT',
                    policy_version='legacy-unversioned', policy_digest='', source='LEGACY_CAPTURED',
                )
                Receipt.objects.using(schema_editor.connection.alias).filter(pk=receipt.pk).update(created_at=date)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requestbudget_securitymutex_uploadadmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='processing_withdrawn_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AccountChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=20)),
                ('activates_account', models.BooleanField(default=False)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('auth_state', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized', models.EmailField(max_length=254, unique=True)),
                ('verified_at', models.DateTimeField(null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=12)),
                ('policy_version', models.CharField(max_length=60)),
                ('policy_digest', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=30)),
                ('request_id', models.UUIDField(default=uuid.uuid4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'request_id'), name='consent_request')],
            },
        ),
        migrations.CreateModel(
            name='MatchSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=100)),
                ('key_digest', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'provider', 'key_digest'), name='suppressed_source')],
            },
        ),
        migrations.RunPython(capture_legacy_receipts, migrations.RunPython.noop),
    ]
