# Generated by Django 5.2.17 on 2026-10-02 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def populate_dispatch(apps, schema_editor):
    Run = apps.get_model('core', 'AnalysisRun')
    Dispatch = apps.get_model('core', 'RunDispatch')
    Slot = apps.get_model('core', 'ExecutionSlot')
    alias = schema_editor.connection.alias
    for run in Run.objects.using(alias).filter(status__in=['QUEUED', 'PROCESSING']).iterator():
        Dispatch.objects.using(alias).get_or_create(run_id=run.pk)
        if run.status == 'PROCESSING':
            Slot.objects.using(alias).create(run_id=run.pk, fence=run.fence, runtime='LEGACY',
                stop_requested_at=django.utils.timezone.now())


def require_stopped(apps, schema_editor):
    Slot = apps.get_model('core', 'ExecutionSlot')
    Asset = apps.get_model('core', 'ReplayAsset')
    if (Slot.objects.using(schema_editor.connection.alias).filter(released_at=None).exists()
        or Asset.objects.using(schema_editor.connection.alias).exclude(storage_provider='LOCAL').exists()):
        raise RuntimeError('Rollback requires all executions stopped and all storage LOCAL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_processing_withdrawn_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='deadline_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='heartbeat_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='phase',
            field=models.CharField(default='QUEUED', max_length=30),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replayasset',
            name='storage_generation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='replayasset',
            name='storage_provider',
            field=models.CharField(default='LOCAL', max_length=12),
        ),
        migrations.CreateModel(
            name='RunDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('task_name', models.CharField(blank=True, max_length=500)),
                ('operation_name', models.CharField(blank=True, max_length=500)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fence', models.PositiveIntegerField()),
                ('runtime', models.CharField(default='LOCAL', max_length=20)),
                ('execution_name', models.CharField(blank=True, max_length=500)),
                ('stop_requested_at', models.DateTimeField(null=True)),
                ('released_at', models.DateTimeField(db_index=True, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.analysisrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'fence'), name='execution_attempt')],
            },
        ),
        migrations.RunPython(populate_dispatch, require_stopped),
    ]
