# Generated by Django 5.2.17 on 2026-10-02 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def refuse_live_budget_rollback(apps, schema_editor):
    Budget = apps.get_model('core', 'RunBudget')
    if Budget.objects.filter(models.Q(state='OPEN') | models.Q(day=django.utils.timezone.localdate(), charged_processing_seconds__gt=0) | models.Q(day=django.utils.timezone.localdate(), charged_media_seconds__gt=0)).exists():
        raise RuntimeError('M17 rollback requires drained holds and expired charged-day budgets')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hosted_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executionslot',
            name='claimed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AttemptMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('queued_seconds', models.FloatField(null=True)),
                ('elapsed_seconds', models.FloatField(null=True)),
                ('coordinator_cpu_seconds', models.FloatField(null=True)),
                ('coordinator_peak_rss_bytes', models.PositiveBigIntegerField(null=True)),
                ('decoder_cpu_seconds', models.FloatField(null=True)),
                ('decoder_peak_rss_bytes', models.PositiveBigIntegerField(null=True)),
                ('source_bytes', models.PositiveBigIntegerField(null=True)),
                ('media_seconds', models.FloatField(null=True)),
                ('derived_bytes', models.PositiveBigIntegerField(null=True)),
                ('outcome', models.CharField(default='PROCESSING', max_length=30)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.executionslot')),
            ],
        ),
        migrations.CreateModel(
            name='CostObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('scope', models.CharField(max_length=12)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('reference', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('component', 'period_start', 'period_end', 'scope'), name='cost_observation_period'), models.CheckConstraint(condition=models.Q(('amount_usd__gte', 0), ('period_end__gte', models.F('period_start')), ('scope__in', ['SYNTHETIC', 'OBSERVED']), ('component__in', ['INFRASTRUCTURE', 'PROVIDER', 'REVIEW', 'SUPPORT'])), name='cost_observation_valid')],
            },
        ),
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField(db_index=True)),
                ('route', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('server_errors', models.PositiveIntegerField(default=0)),
                ('throttled', models.PositiveIntegerField(default=0)),
                ('seconds', models.FloatField(default=0)),
                ('max_seconds', models.FloatField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('minute', 'route'), name='request_metric_bucket')],
            },
        ),
        migrations.CreateModel(
            name='OperatorWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=12)),
                ('seconds', models.PositiveIntegerField()),
                ('scope', models.CharField(default='SYNTHETIC', max_length=12)),
                ('request_id', models.UUIDField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'request_id'), name='operator_work_request'), models.CheckConstraint(condition=models.Q(('scope__in', ['SYNTHETIC', 'OBSERVED']), ('kind__in', ['REVIEW', 'SUPPORT']), ('seconds__gt', 0), ('seconds__lte', 28800)), name='operator_work_valid')],
            },
        ),
        migrations.CreateModel(
            name='RunBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('state', models.CharField(default='OPEN', max_length=10)),
                ('reserved_media_seconds', models.PositiveIntegerField(default=600)),
                ('reserved_processing_seconds', models.PositiveIntegerField()),
                ('charged_media_seconds', models.PositiveIntegerField(default=0)),
                ('charged_processing_seconds', models.PositiveIntegerField(default=0)),
                ('settled_at', models.DateTimeField(null=True)),
                ('measurement_complete', models.BooleanField(default=False)),
                ('attempt_seconds', models.PositiveIntegerField(default=420)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.analysisrun')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['OPEN', 'CLOSED'])), name='run_budget_state')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_live_budget_rollback),
    ]
