# Generated by Django 5.2.17 on 2026-10-02 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_operations_budgets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['owner', '-played_at', '-id'], name='history_owner_played'),
        ),
    ]
