# Generated by Django 5.2.17 on 2026-10-02 15:53

from django.db import migrations, models


def clear_unmeasured_dates(apps, schema_editor):
    Slot = apps.get_model('core', 'ExecutionSlot')
    Slot.objects.filter(attemptmetric__isnull=True).update(claimed_at=None)


def refuse_unknown_date_rollback(apps, schema_editor):
    Slot = apps.get_model('core', 'ExecutionSlot')
    if Slot.objects.filter(claimed_at=None).exists():
        raise RuntimeError('Unknown historical attempt dates cannot be replaced with invented dates on rollback')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_history_query_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionslot',
            name='claimed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(clear_unmeasured_dates, refuse_unknown_date_rollback),
    ]
