# Generated by Django 5.2.17 on 2026-10-02 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_reverse(apps, schema_editor):
    if apps.get_model('core', 'PilotStudy').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Refusing to drop pilot history; use a reviewed forward change')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_preserve_unknown_attempt_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotGateReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(max_length=2)),
                ('revision', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('invalidated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PilotEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=16)),
                ('pseudonym', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('split', models.CharField(default='development', max_length=16)),
                ('state', models.CharField(default='ACTIVE', max_length=12)),
                ('consent_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('evaluation_digest', models.CharField(blank=True, max_length=64)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.improvementevaluation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PilotDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=12)),
                ('reason', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pilotenrollment')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pilotgatereport')),
            ],
        ),
        migrations.CreateModel(
            name='PilotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('phase', models.CharField(max_length=16)),
                ('played_at', models.DateTimeField()),
                ('playable_seconds', models.PositiveIntegerField(null=True)),
                ('state', models.CharField(max_length=20)),
                ('unaided', models.BooleanField(default=False)),
                ('setup_seconds', models.PositiveIntegerField(null=True)),
                ('useful', models.BooleanField(null=True)),
                ('insight_seconds', models.PositiveIntegerField(null=True)),
                ('request_id', models.UUIDField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pilotenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='PilotCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('game_build', models.CharField(blank=True, max_length=80)),
                ('duration_seconds', models.FloatField()),
                ('withdrawn_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.replayasset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pilotsession')),
            ],
        ),
        migrations.CreateModel(
            name='PilotStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=80)),
                ('dataset_kind', models.CharField(max_length=12)),
                ('protocol', models.JSONField()),
                ('protocol_digest', models.CharField(max_length=64)),
                ('state', models.CharField(default='COLLECTING', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('request_id', models.UUIDField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pilotgatereport',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pilotstudy'),
        ),
        migrations.AddField(
            model_name='pilotenrollment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pilotstudy'),
        ),
        migrations.CreateModel(
            name='PilotTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=12)),
                ('start_us', models.PositiveBigIntegerField()),
                ('end_us', models.PositiveBigIntegerField()),
                ('prediction', models.JSONField(null=True)),
                ('request_id', models.UUIDField()),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.pilotenrollment')),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pilotcapture')),
                ('reviewer_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.pilotenrollment')),
                ('reviewer_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.pilotenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='PilotReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField()),
                ('label_digest', models.CharField(max_length=64)),
                ('seconds', models.PositiveIntegerField()),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pilotenrollment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pilottask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pilotsession',
            constraint=models.UniqueConstraint(fields=('enrollment', 'code'), name='pilot_session_code'),
        ),
        migrations.AddConstraint(
            model_name='pilotsession',
            constraint=models.UniqueConstraint(fields=('enrollment', 'request_id'), name='pilot_session_request'),
        ),
        migrations.AddConstraint(
            model_name='pilotcapture',
            constraint=models.UniqueConstraint(fields=('session', 'asset'), name='pilot_capture_source'),
        ),
        migrations.AddConstraint(
            model_name='pilotstudy',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='pilot_study_request'),
        ),
        migrations.AddConstraint(
            model_name='pilotstudy',
            constraint=models.CheckConstraint(condition=models.Q(('dataset_kind__in', ['synthetic', 'real']), ('state__in', ['COLLECTING', 'FROZEN', 'CLOSED'])), name='pilot_study_valid'),
        ),
        migrations.AddConstraint(
            model_name='pilotgatereport',
            constraint=models.UniqueConstraint(fields=('study', 'gate', 'revision'), name='pilot_gate_revision'),
        ),
        migrations.AddConstraint(
            model_name='pilotenrollment',
            constraint=models.UniqueConstraint(fields=('study', 'owner'), name='pilot_one_role'),
        ),
        migrations.AddConstraint(
            model_name='pilotenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['PARTICIPANT', 'REVIEWER', 'ADJUDICATOR', 'EXPERT']), ('state__in', ['ACTIVE', 'WITHDRAWN']), ('split__in', ['development', 'validation', 'held-out'])), name='pilot_enrollment_valid'),
        ),
        migrations.AddConstraint(
            model_name='pilottask',
            constraint=models.UniqueConstraint(fields=('capture', 'request_id'), name='pilot_task_request'),
        ),
        migrations.AddConstraint(
            model_name='pilottask',
            constraint=models.CheckConstraint(condition=models.Q(('end_us__gte', models.F('start_us')), ('kind__in', ['QC', 'TARGET', 'TRIAL'])), name='pilot_task_valid'),
        ),
        migrations.AddConstraint(
            model_name='pilotreview',
            constraint=models.UniqueConstraint(fields=('task', 'reviewer'), name='pilot_independent_review'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
