# Generated by Django 5.2.17 on 2026-10-02 16:57

from django.db import migrations, models


def guard_reverse(apps, schema_editor):
    if apps.get_model('core', 'PilotCapture').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Refusing to discard pilot retention pins; use a reviewed forward change')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pilot_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotcapture',
            name='original_retain_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
