# Generated by Django 5.2.17 on 2026-10-02 17:10

from django.db import migrations, models


def guard_reverse(apps, schema_editor):
    if apps.get_model('core', 'PilotEnrollment').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Refusing to discard prospective allocation; use a reviewed forward change')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pilot_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotenrollment',
            name='comparison_order',
            field=models.CharField(default='UNASSIGNED', max_length=20),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
