# Generated by Django 5.2.17 on 2026-10-03 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_reverse(apps, schema_editor):
    Session = apps.get_model('core', 'UploadSession')
    if Session.objects.using(schema_editor.connection.alias).filter(~models.Q(state='CANCELLED') | models.Q(asset__purge_completed_at=None)).exists():
        raise ValueError('Cancel/purge upload sessions before reversing M06 storage migration')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pilot_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replayasset',
            name='upload_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField()),
                ('claim_digest', models.CharField(max_length=64)),
                ('expected_sha256', models.CharField(max_length=64)),
                ('expected_md5', models.CharField(max_length=24)),
                ('received_bytes', models.PositiveBigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(default='INITIALIZING', max_length=20)),
                ('fence', models.PositiveIntegerField(default=0)),
                ('verification_lease', models.DateTimeField(null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.replayasset')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.match')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'request_id'), name='upload_session_request'), models.CheckConstraint(condition=models.Q(('state__in', ['INITIALIZING', 'UPLOADING', 'VERIFYING', 'COMPLETE', 'PURGING', 'CANCELLED'])), name='upload_session_state')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
