# Generated by Django 5.2.17 on 2026-10-03 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_reverse(apps, schema_editor):
    alias = schema_editor.connection.alias
    if (
        apps.get_model('core', 'KnowledgeProposal').objects.using(alias).exists()
        or apps.get_model('core', 'KnowledgeReanalysis').objects.using(alias).exists()
        or apps.get_model('core', 'GameplayEvent').objects.using(alias).exclude(measurement={}).exists()
    ):
        raise ValueError('Export/erase governed history before reversing M07; removing version pins would change historical evidence')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_resumable_uploads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayevent',
            name='measurement',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='definitionversion',
            name='kind',
            field=models.CharField(choices=[('build', 'build'), ('move', 'move'), ('knowledge', 'knowledge'), ('situation', 'situation'), ('metric', 'metric'), ('drill', 'drill'), ('capture', 'capture'), ('compatibility', 'compatibility')], max_length=30),
        ),
        migrations.CreateModel(
            name='KnowledgeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=160, unique=True)),
                ('kind', models.CharField(max_length=30)),
                ('dataset_kind', models.CharField(max_length=12)),
                ('payload', models.JSONField()),
                ('provenance', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('state', models.CharField(default='OPEN', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=30)),
                ('request_id', models.UUIDField()),
                ('game_build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gamebuild')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('published', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.definitionversion')),
                ('reviewer_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.replayasset')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.knowledgeproposal')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeReanalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('request_id', models.UUIDField()),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.definitionversion')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.match')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.analysisrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.definitionversion')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(max_length=12)),
                ('note', models.TextField(max_length=2000)),
                ('proposal_hash', models.CharField(max_length=64)),
                ('request_id', models.UUIDField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.knowledgeproposal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='knowledgeproposal',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='knowledge_proposal_request'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewer_one', models.F('reviewer_two')), _negated=True), models.Q(('owner', models.F('reviewer_one')), _negated=True), models.Q(('owner', models.F('reviewer_two')), _negated=True)), name='knowledge_independent_reviewers'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeevidence',
            constraint=models.UniqueConstraint(fields=('proposal', 'asset'), name='knowledge_source'),
        ),
        migrations.AddConstraint(
            model_name='knowledgereanalysis',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='knowledge_reanalysis_request'),
        ),
        migrations.AddConstraint(
            model_name='knowledgereview',
            constraint=models.UniqueConstraint(fields=('proposal', 'owner'), name='knowledge_review_once'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
