# Generated by Django 5.2.17 on 2026-10-05 16:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def pin_existing(apps, schema_editor):
    Assignment = apps.get_model("core", "DrillAssignment")
    for item in Assignment.objects.select_related("drill").iterator():
        Assignment.objects.filter(pk=item.pk).update(drill_hash=item.drill.content_hash)


def guard_history(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError

    Assignment = apps.get_model("core", "DrillAssignment")
    if (
        apps.get_model("core", "PracticeLog").objects.exists()
        or Assignment.objects.filter(request_id__isnull=False).exists()
        or Assignment.objects.exclude(diagnosis={}).exists()
        or apps.get_model("core", "TrainingSession")
        .objects.filter(request_id__isnull=False)
        .exists()
        or apps.get_model("core", "DefinitionVersion")
        .objects.filter(payload__has_key="practice_workflow")
        .exists()
    ):
        raise IrreversibleError("M11 practice history requires a reviewed forward migration")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_dataset_operations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.UUIDField()),
                ("state", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                ("reported_attempts", models.PositiveIntegerField(null=True)),
                ("obstacle", models.CharField(default="NONE", max_length=24)),
                ("pins", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="drillassignment",
            name="diagnosis",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="drillassignment",
            name="drill_hash",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="drillassignment",
            name="request_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="request_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddConstraint(
            model_name="drillassignment",
            constraint=models.UniqueConstraint(
                fields=("owner", "request_id"), name="unique_assignment_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingsession",
            constraint=models.UniqueConstraint(
                fields=("owner", "request_id"), name="unique_practice_request"
            ),
        ),
        migrations.AddField(
            model_name="practicelog",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.drillassignment"
            ),
        ),
        migrations.AddField(
            model_name="practicelog",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="practicelog",
            constraint=models.UniqueConstraint(
                fields=("owner", "request_id"), name="unique_practice_log_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="practicelog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["COMPLETED", "INTERRUPTED", "SKIPPED", "DELETED"])
                ),
                name="valid_practice_log_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="practicelog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state", "DELETED"),
                    models.Q(
                        ("ended_at__isnull", False),
                        ("reported_attempts__isnull", False),
                        ("started_at__isnull", False),
                        ("ended_at__gte", models.F("started_at")),
                        ("reported_attempts__lte", 2000),
                    ),
                    _connector="OR",
                ),
                name="practice_log_bounded_times",
            ),
        ),
        migrations.RunPython(pin_existing, migrations.RunPython.noop),
        migrations.RunPython(migrations.RunPython.noop, guard_history),
    ]
