# Generated by Django 5.2.17 on 2026-10-05 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_history(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError

    Plan = apps.get_model("core", "EvaluationPlan")
    if (Plan.objects.exclude(protocol={}).exists() or Plan.objects.filter(request_id__isnull=False).exists()
            or apps.get_model("core", "ComparisonSession").objects.exists()
            or apps.get_model("core", "ImprovementEvaluation").objects.filter(phase="RETENTION").exists()):
        raise IrreversibleError("M12 frozen schedules/session/retention history needs a reviewed forward migration")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reviewed_practice_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.CharField(max_length=16)),
                ('session_key', models.CharField(max_length=64)),
                ('code', models.CharField(default='', max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('request_id', models.UUIDField()),
                ('state', models.CharField(max_length=16)),
                ('played_at', models.DateTimeField(null=True)),
                ('match_ids', models.JSONField(default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('input_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='evaluationplan',
            name='input_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='evaluationplan',
            name='protocol',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='evaluationplan',
            name='request_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='improvementevaluation',
            name='phase',
            field=models.CharField(default='FOLLOWUP', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='evaluationplan',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='unique_plan_request'),
        ),
        migrations.AddField(
            model_name='comparisonsession',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparisonsession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evaluationplan'),
        ),
        migrations.AddConstraint(
            model_name='comparisonsession',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='unique_comparison_session_request'),
        ),
        migrations.AddConstraint(
            model_name='comparisonsession',
            constraint=models.UniqueConstraint(fields=('plan', 'phase', 'session_key', 'revision'), name='unique_comparison_session_revision'),
        ),
        migrations.AddConstraint(
            model_name='comparisonsession',
            constraint=models.CheckConstraint(condition=models.Q(('phase__in', ['FOLLOWUP', 'RETENTION'])), name='valid_comparison_phase'),
        ),
        migrations.AddConstraint(
            model_name='comparisonsession',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['RECORDED', 'MISSING', 'SKIPPED', 'DELETED'])), name='valid_comparison_session_state'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_history),
    ]
