# Generated by Django 5.2.17 on 2026-10-05 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_history(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError

    if any(apps.get_model('core', name).objects.exists() for name in ('DetectorVersion', 'RecognitionRun', 'DetectorReview')):
        raise IrreversibleError('M09 immutable detector/review/evidence history needs a reviewed forward migration')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_longitudinal_comparison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=160)),
                ('manifest', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('state', models.CharField(default='REGISTERED', max_length=16)),
                ('request_id', models.UUIDField()),
                ('activated_at', models.DateTimeField(null=True)),
                ('disabled_reason', models.CharField(blank=True, max_length=40)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datasetcollection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewer_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detector_review_one', to=settings.AUTH_USER_MODEL)),
                ('reviewer_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detector_review_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField()),
                ('inputs', models.JSONField()),
                ('report', models.JSONField()),
                ('input_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('invalidated_at', models.DateTimeField(null=True)),
                ('reason', models.CharField(blank=True, max_length=40)),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.detectorversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datasetsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='DetectorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(max_length=10)),
                ('report_hash', models.CharField(max_length=64)),
                ('request_id', models.UUIDField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.recognitionrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='detectorversion',
            constraint=models.UniqueConstraint(fields=('owner', 'version'), name='detector_owner_version'),
        ),
        migrations.AddConstraint(
            model_name='detectorversion',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='detector_request'),
        ),
        migrations.AddConstraint(
            model_name='detectorversion',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'ACTIVE')), fields=('dataset',), name='detector_active_dataset'),
        ),
        migrations.AddConstraint(
            model_name='detectorversion',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['REGISTERED', 'ACTIVE', 'DISABLED', 'INVALIDATED'])), name='detector_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='recognitionrun',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='recognition_run_request'),
        ),
        migrations.AddConstraint(
            model_name='detectorreview',
            constraint=models.UniqueConstraint(fields=('run', 'owner'), name='detector_independent_review'),
        ),
        migrations.AddConstraint(
            model_name='detectorreview',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='detector_review_request'),
        ),
        migrations.AddConstraint(
            model_name='detectorreview',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['APPROVE', 'REJECT'])), name='detector_review_valid'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_history),
    ]
