# Generated by Django 5.2.17 on 2026-10-06 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_history(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError

    if any(apps.get_model('core', name).objects.exists() for name in ('RecordingDevice', 'DevicePairing', 'RecordingReceipt')):
        raise IrreversibleError('Recording authorization and deletion suppression need a reviewed forward migration')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_recognition_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=60)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordingDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=60)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('last_seen_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordingReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key_digest', models.CharField(max_length=64)),
                ('request_id', models.UUIDField(default=uuid.uuid4)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recordingdevice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.uploadsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'key_digest'), name='recording_byte_receipt')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_history),
    ]
