# Generated by Django 5.2.17 on 2026-10-06 15:24

from django.db import migrations, models


def guard_suppression(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError

    if apps.get_model('core', 'RecordingReceipt').objects.filter(suppressed=True).exists():
        raise IrreversibleError('Manual byte suppression needs a reviewed forward migration')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_recording_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingreceipt',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_suppression),
    ]
